### ISSUE TITLE
Connection failed: URL error: Unable to connect to wss://192.168.99.100:2380/stream, retrying in 60s

### ISSUE THREAD

**Issue by juan11perez** [desbma/gotify-desktop#10]
Good day, first thank you for this component.

Im getting the following error

```
WARN  [gotify_desktop::gotify] Connection failed: URL error: Unable to connect to wss://192.168.99.100:2380/stream, retrying in 60s
```
my docker compose is as follows:

```
  gotify:
    container_name: gotify
    image: gotify/server:latest
    restart: unless-stopped
    hostname: UNRAID
    network_mode: appdata_mynet
    volumes:
    - /mnt/cache/appdata/gotify:/app/data 
    env_file: secrets/.env
    ports:
    - "2380:80" 
```

```
[gotify]
url = "wss://192.168.99.100:2380"
token = "mytoken"
auto_delete = true  # optional, if true, deletes messages that have been handled, defaults to false
```
