### ISSUE TITLE
[Feature Request] Perform action (run script, etc) on message keyword / priority

### ISSUE THREAD

**Issue by MostHated** [desbma/gotify-desktop#5]
Hey there,
    Been using the app for a few weeks now and it has been working well. One thing I have been wishing to have is a way to have notifications be actionable. Such as, if a notification comes in that has a specific keyword in the message, be able to run a specific script tied to that keyword. 

Ex. A message comes in as:

```json
{{ "title": "Error Notice", "message": "build_failed", "priority": 8 }}
```
Then perhaps in the config, it could be setup something like this:

```toml
[gotify]
url = "wss://SERVER_DOMAIN:SERVER_PORT"
token = "YOUR_SECRET_TOKEN"
auto_delete = true  # optional, if true, deletes messages that have been handled, defaults to false

[notification]
min_priority = 1  # optional, ignores messages with priority lower than given value
notification_on_action = 0     # 0 = Only perform action, don't show notification. 1 = Perform action and show notification.

# Priority would be 1-2, 3-4, 5-6, 7-8, 9-10 each pair could count as one "level", and trigger for anything above that level if no other higher-level exists.
# Ex. only [actions.priority_4] exists, but a message comes in with a priority of 9, it would still fire off the priority_4 action, since no other higher ones existed.
# It would also fire off if a priority_3 message came in, since 3-4 are the same "level", but would not fire off if a priority_2 message came in that matched the keyword.

[actions] 

[actions.priority_1]
build_failed = "$HOME/scripts/build_succeeded.sh" #  <-- Action to perform if keyword is matched
#    ^ keyword in which to perform action, if present in message body

[actions.priority_3]
build_failed = "$HOME/scripts/build_warning.sh"

[actions.priority_5]
build_failed = "$HOME/scripts/build_failed.sh"

[actions.priority_7]
build_failed = "$HOME/scripts/build_failed_hard.sh"
```
The above is based on how I think I remember Toml's slightly more advanced features working, but I could be mistaken. Hopefully, it makes sense.

To be honest, if you simply don't feel like doing something like this, that is no problem, just let me know. I have been dabbling into Rust the last few days and might see if I can do something like this myself, even if this feature *is* implemented, just to have a learning goal to work toward. 

Thanks
-MH
